### ISSUE TITLE
.findDOMNode

### ISSUE THREAD

**Issue by baicuhaha** [eisneim/react-html5-video#4]
index.js:63846 Uncaught TypeError: _react2.default.findDOMNode is not a function   why?   

![2016-08-12 6 48 39](https://cloud.githubusercontent.com/assets/20334376/17620242/84b8c3f8-60bd-11e6-9d51-8002e17c4566.png)
![2016-08-12 6 48 46](https://cloud.githubusercontent.com/assets/20334376/17620243/85c88f80-60bd-11e6-9dd5-d77dfc6fe5ef.png)

**Comment by eisneim** [comment]
make sure you are using: _ReactDOM.findDOMNode_ instead of _React.findDOMNode_ in your code

**Comment by harinair** [comment]
Basically the npm has older version. It is still using older React with React.findDOMNode(). Basically I have to download latest code to make it work.

**Comment by eisneim** [comment]
@baicuhaha new release published on npm
